steps:
  - label: "Testspace setup"
    command: |
      testspace config url munderseth.testspace.com
    key: "setup"
  - label: ":hammer: Build"
    command: |
      call npm install
      call npm test
      testspace junit.xml{tests}
    key: "build"
    depends_on: "setup"


