steps:
  - label: ":hammer: Build"
    commands:
      - call npm install
      - call npm test
      - |
        testspace config url munderseth.testspace.com
        testspace junit.xml{tests}
    key: "build"


