steps:
  - label: ":hammer: Build"
    commands:
      - npm install
      - npm test
      - |
        testspace config url munderseth.testspace.com
        testspace junit.xml{tests}
    key: "build"


